name: hello_world
description: A medical companion app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter_country_picker: 0.1.6
  flutter_datetime_picker: 1.3.8
  flutter_snake_navigationbar: 0.3.0
  intl: 0.16.1
  flutter:
    sdk: flutter
  simple_animations: 1.3.12
  google_maps_flutter: 0.5.27+2
  geolocator: 5.3.1
  location: 3.0.2
  geocoder: 0.2.1
  table_calendar: 2.2.3
  flutter_svg: 0.17.4
  curved_navigation_bar: 0.3.2
  font_awesome_flutter: 8.8.1
  get_it: 4.0.1
  flutter_dialogflow: 0.1.3
  flutter_local_notifications: 1.4.3
  autocomplete_textfield: 1.7.3
  json_annotation: 3.0.1
  charts_flutter: 0.9.0
  maps_launcher: 1.2.0
  flutter_staggered_grid_view: 0.3.0
  flutter_sparkline: 0.1.0
  flutter_circular_chart: 0.1.0
  image_picker: 0.6.6+1
  flutter_calendar_carousel: 1.4.12
  auto_size_text: 2.1.0
  timeline_tile: 0.1.2
  google_fonts: 1.1.0

  # Firebase FCM
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_messaging: ^6.0.13


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: any
  provider: ^4.0.4
  shared_preferences: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/
   - assets/login_art.png
   - assets/logo_highres_v2.png
   - assets/static_data/
   - assets/icons/
   - assets/fonts/
   - assets/static_data/credentials.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/Poppins-Medium.ttf 
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
